print("---suatu hari---")
input("kaka :nama kamu siapa ? ")
sekolah_dmn =input("kaka :sekolah dimana ? ")
print (" ~kaka berkata =")
print(sekolah_dmn, " wah bagus dong")
int(input("kelas berapa ? "))
kendaraan =input(" ke sekolah naik apa ? ")
print(" bagus deh naik ", kendaraan )
print(" wah keren naik ",kendaraan)
